# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wGNdT5ZxVI8eZMbcr6wiVdqrRxfu1Ts8
"""

import pandas as pd
from collections import Counter
import plotly.graph_objects as go

classmates = pd.read_csv("course_pathways.csv")
course_menu = pd.read_csv("course_catalog_by_major.csv")

crew = classmates[
    (classmates["Program"] == "CECS") &
    (classmates["Major"].isin(["Data science", "Artificial intelligence", "Cybersecurity"]))
].copy()

def get_mandatory_only(row):
    track = row["Major"]
    full_journey = row["CoursePath"].split(" -> ")
    must_take = course_menu[
        (course_menu["Major"] == track) & (course_menu["Type"] == "Required")
    ]["Course"].tolist()
    return [stop for stop in full_journey if stop in must_take]

crew["Journey"] = crew.apply(get_mandatory_only, axis=1)
crew = crew[crew["Journey"].map(len) > 1]

route_counter = Counter()
for trip in crew["Journey"]:
    for i in range(len(trip) - 1):
        route = (trip[i], trip[i+1])
        route_counter[route] += 1

path_map = pd.DataFrame([
    {"source": a, "target": b, "value": count}
    for (a, b), count in route_counter.items()
])

path_map = path_map[path_map["value"] > 1]

bus_stops = list(set(path_map["source"]).union(set(path_map["target"])))
stop_ids = {stop: i for i, stop in enumerate(bus_stops)}

path_map["source_idx"] = path_map["source"].map(stop_ids)
path_map["target_idx"] = path_map["target"].map(stop_ids)

fig = go.Figure(data=[go.Sankey(
    arrangement='snap',
    node=dict(
        pad=20,
        thickness=20,
        line=dict(color="black", width=0.5),
        label=bus_stops
    ),
    link=dict(
        source=path_map["source_idx"],
        target=path_map["target_idx"],
        value=path_map["value"]
    )
)])

fig.update_layout(
    title_text="CECS required course by major",
    font_size=12,
    margin=dict(l=20, r=20, t=50, b=20)
)

fig.show()